### PR TITLE
EPMLABSBRN-256  - update ember frontend to octane blueprint

### PR DESCRIPTION
**Pull request by lifeart**
Updated app layout and deps to satisfy octane

### CODE REVIEW

**Comment by iki6** [comment]
everything works fine, except:

1. the general view:

brainUp

2. progress items are still calculating their positions after the component is rendered:

brainUpProgressItems

3. we had a progress items shift in case there are too many of them for the progress container width)
before:

progressItemsShift

after: 

progressItemsShift2

**Comment by ElenaSpb** [comment]
could you please name MR accoding our rules with task Name and description
https://github.com/Brain-up/brn/wiki/Coding-Standards

**Comment by lifeart** [comment]
@ElenaSpb could you please provide task name

**Comment by ElenaSpb** [comment]
> @ElenaSpb could you please provide task name?

https://jira.epam.com/jira/browse/EPMLABSBRN-256 get this one please. 
also you or Artem can create such tasks by  yourself in this style with such labels, thanks

**Comment by lifeart** [comment]
https://github.com/Brain-up/brn/pull/231

**Pull request closed without merging**
