### PR TITLE
EPMLABSBRN-654: HTTPS initial configs

### PR DESCRIPTION
**Pull request by vfaspb**
[EPMLABSBRN-654](https://jira.epam.com/jira/browse/EPMLABSBRN-654)

HTTPS initial configs

[Documentation](https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose-ru) from we took proposal for this change

- [x] divide epam/vscale compose and nginx config file (default.conf file should be without https, with 80 port for local development and epam instance)
- [x] add config in github action to deploy different envs with different compose/nginx-config files based on env variables
- [x] prepare action to trigger renew cert on schedule like described [here](https://jasonet.co/posts/scheduled-actions/)

### CODE REVIEW

**Review by DmitriyStoyanov — APPROVED** [review]

**Comment by DmitriyStoyanov** [comment]
Possible need to divide between epam and vscale.io compose files

**Review by DmitriyStoyanov — CHANGES_REQUESTED** [review]
need to split docker-compose files for different envs epam/vscale
On epam we should'nt use certbot with https. and there will be only 80 port for this app

**Review by ElenaSpb — APPROVED** [review]

**Comment by vfaspb** [comment]
> [EPMLABSBRN-654](https://jira.epam.com/jira/browse/EPMLABSBRN-654)
> 
> HTTPS initial configs
> 
> [Documentation](https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose-ru) from we took proposal for this change
> 
> * [ ]  divide epam/vscale compose and nginx config file (default.conf file should be without https, with 80 port for local development and epam instance)
> * [ ]  add config in github action to deploy different envs with different compose/nginx-config files based on env variables
> * [ ]  prepare action to trigger renew cert on schedule like described [here](https://jasonet.co/posts/scheduled-actions/)

Done. However I'm not sure about renew action. The fact is that after cert renew we have to restart nginx and I decided just redeploy container. But I'm not really sure that it is a best solution

**Review by DmitriyStoyanov — APPROVED** [review]
All looks good from me
We can start testing it

**Pull request merged**
